name: Cypress tests
on: [pull_request]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Compile TypeScript and Build App
        run: npm run build
      - name: Start server
        run: node public/server.js
        env: 
          COOKIE_SESSIONS_SECRET: ${{secrets.COOKIE_SESSIONS_SECRET}}
          GOOGLE_CLIENT_ID: ${{secrets.GOOGLE_CLIENT_ID}}
          GOOGLE_CLIENT_SECRET: ${{secrets.GOOGLE_CLIENT_SECRET}}
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          install: false
          wait-on: 'http://localhost:4000/'
          record: true
          parallel: true
