name: Cypress tests
on: [pull_request]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: node public/server.js
          wait-on: 'http://localhost:4000'
          env: true
        env: 
          CYPRESS_COOKIE_SESSIONS_SECRET: ${{secrets.COOKIE_SESSIONS_SECRET}}
          CYPRESS_GOOGLE_CLIENT_ID: ${{secrets.GOOGLE_CLIENT_ID}}
          CYPRESS_GOOGLE_CLIENT_SECRET: ${{secrets.GOOGLE_CLIENT_SECRET}}
