name: Cypress tests
on: [pull_request]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    env: 
      COOKIE_SESSIONS_SECRET: ${{ secrets.COOKIE_SESSIONS_SECRET }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: npm install

      - name: Compile TS --> JS then Build React App
        run: npm run build

      - name: Spin up server
        run: GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} node public/server.js

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          install: false
          wait-on: 'http://localhost:4000/'
          record: true
          parallel: true
