name: Validate solutions to puzzles
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm i
    - name: Convert ts --> js
      run: tsc
    - name: Check puzzles
      run: node public/utils/validatePuzzleSolutions.js